### ISSUE TITLE
64 bit int not supported

### ISSUE THREAD

**Issue by arntzy** [sy1vain/omxplayer#1]
I'm getting the following error when trying to use the module:

events.js:160
      throw er; // Unhandled 'error' event
      ^

```
Error: 64 Bit integers not supported
    at Object.MakeSimpleMarshaller.marshaller.check (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshallers.js:181:23)
    at Object.MakeSimpleMarshaller.marshaller.marshall [as marshall] (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshallers.js:184:22)
    at writeSimple (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:112:20)
    at write (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:92:14)
    at writeStruct (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:32:5)
    at module.exports (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:17:13)
    at Object.marshallMessage [as marshall] (/home/cactus/omxplayer/node_modules/dbus-native/lib/message.js:83:16)
    at EventEmitter.<anonymous> (/home/cactus/omxplayer/node_modules/dbus-native/index.js:126:29)
    at EventEmitter.g (events.js:291:16)
    at emitNone (events.js:86:13)
```

The video keeps playing, but the error that's thrown crashes the node app.

**Comment by sy1vain** [comment]
Hi, what are you trying to do when this happens? Or what is the event that causes it. It is possibly a problem with the underlying dbus library, as per your issue here: sidorares/node-dbus#149

But still curious when it happens and if we need to build a check or fix around it.

**Comment by Craigson** [comment]
hi @sy1vain, I'm working on the abovementioned issue with @arntzy.  It is likely an issue with dbus-native, but perhaps you have some input that i'm missing.

I simply cloned your repo, did an 'npm install', changed the path to my video file inside api.js and then ran the script.

I commented out the 64bit check in the dbus-native libs, as per the maintainers suggestion, but I still get the following error:
```
** poll **
(node:1442) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): no matching process found
(node:1442) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): no matching process found
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
u
[marshallers.js] inside MakeSimpleMarshaller
u
[marshallers.js] inside MakeSimpleMarshaller
u
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
g
[marshallers.js] inside MakeSimpleMarshaller
o
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
g
[marshallers.js] inside MakeSimpleMarshaller
s
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
g
[marshallers.js] inside MakeSimpleMarshaller
s
[marshallers.js] inside MakeSimpleMarshaller
y
[marshallers.js] inside MakeSimpleMarshaller
g
[marshallers.js] inside MakeSimpleMarshaller
s
[marshallers.js] inside MakeSimpleMarshaller
o
[marshallers.js] inside MakeSimpleMarshaller
x
events.js:160
      throw er; // Unhandled 'error' event
      ^

ReferenceError: type is not defined
    at Object.MakeSimpleMarshaller (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshallers.js:218:60)
    at writeSimple (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:111:38)
    at write (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:92:14)
    at writeStruct (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:32:5)
    at module.exports (/home/cactus/omxplayer/node_modules/dbus-native/lib/marshall.js:17:13)
    at Object.marshallMessage [as marshall] (/home/cactus/omxplayer/node_modules/dbus-native/lib/message.js:83:16)
    at EventEmitter.<anonymous> (/home/cactus/omxplayer/node_modules/dbus-native/index.js:126:29)
    at EventEmitter.g (events.js:291:16)
    at emitNone (events.js:86:13)
    at EventEmitter.emit (events.js:185:7)
```

Note, the video continues to run because the omxplayer process isn't interrupted, but the node script is crashing meaning I no longer have any control over the video, which is obviously what I'm after. Have you ever run into these issues with dbus before?

**Comment by sy1vain** [comment]
Not that I recall. 

Which of the two examples are you running and on which device / platform / node version. Haven't been able to reproduce yet, so might have to test on a setup that corresponds more with yours.

**Comment by Craigson** [comment]
Running a Pi 3 Model B, Rasbian Jessie Lite, Node v6.9.5, npm 3.10.10.
What platform are you testing on?

I tried running examples/api.js and examples/apiPromise.js, both crash with the same errors.

**Comment by sy1vain** [comment]
I will try to fire up a similar system over the weekend.

**Comment by Craigson** [comment]
What system have you successfully run it on and I will try replicate on my end..

**Comment by Craigson** [comment]
and thank you!

**Comment by sy1vain** [comment]
Mostly the same, not sure about the precise node version. But I haven't tested the example file in a while. SO i need to specifically test that.

I also see that node-dbus has recently bumped some versions of underlying dependencies, so that is something I am going to delve into as well.

**Comment by Craigson** [comment]
As an update - the error is being thrown by one of the gettter/setter functions, though I haven't gone through them one by one to determine exactly which one it is.  I can successfully pay/pause the videofile without it crashing.

As an aside, the setPosition() method does not work correctly.  I get an error message "Didn't write bytes to closed stream" after calling it and attempting to play the file.

I'm trying to use omxplayer to play do synchronized playback of the same video file over multiple Pis/displays.  There doesn't seem to be any way to restart the file, or play it from the beginning, without letting the video loop by itself (which is not what I want).  This doesn't have anything to do with your implementation, but seems to be a limitation of omxplayer itself.  Do you know any way around this?  For example, I'd like to send an OSC message to each of the devices to the effect of "restart video" for each display, but from my explorations thus far that doesn't seem possible..

**Comment by sy1vain** [comment]
Update: the problem happens somewhere in the the updated version up dbus-native. When installing version 0.2.0 the problem does not occur. The dbus-specification for OXMPlayer needs 64bit ints. So as a quick fix for now I am going to lock in version 0.2.0 in the dependencies.

**Comment by sy1vain** [comment]
And as a response to your use-case. I have used this module to create multiple sync-running video players. The last time for this theatre-production: http://www.phobiarama.com

I am not sure where you are running into problems. I know that if omxplayer is started with an offset time it will loop back to that time instead of the beginning of the file. That is an implementation of omxplayer. It should however be possible to seek in video and jump to desired position. How the video is encoded is important here since it will jump to the nearest keyframes. Having multiple devices run sync works best with a high keyframe rate and a constant bitrate, which makes looking for a position in the file more predictable and precise.

To restart a video, you should be able to send it a setPosition command with 0 as the postion. Note the difference between seek and setPosition: seek is relative and setPosition is absolute.

**Comment by Craigson** [comment]
Thanks @sy1vain!

Perhaps it was issues with the encoding as I was having issues with both seek and setPosition.  I'll update you of any progress on my end.

Thanks again for the help.
